# GIT TIL 22

### 예외 처리

>예외는 클래스로 미리 정의되어 있는 것이다

1. try-except 구문을 사용해서 예외를 처리

```python
try:
    pass
    #실제로 내가 뭔가 실행하고 싶은 로직

except Error:
    pass
# 예외가 발생하면 except로 실행시킨다.
```

- 위에 둘은 기본적인 예외 처리 구문이고
아래는 선택사항이다.

```python
else:
    pass
# 예외가 발생하지 않으면 else로 실행시킨다.

finally:
    pass
# 파이널리는 최종 정리 구문이다.

# 이 둘은 선택적으로 사용할 수 있다.
```

<br>

2. 실제 사용 예시
```python
try:
    number = input("숫자를 입력하세요 : ")
    print(int(number))
    # 숫자 말고 문자를 입력하면 예외가 발생한다.
    # 에러 메세지에서 ValueError라고 나온다.

except ValueError: # ValueError라는 예외를 처리한다.
    print("제발 ,, 숫자만 입력하라고 ,,")

except ValueError as err: # 원본 에러 메시지도 출력해준다.
    print("제발 ,, 숫자만 입력하라고 ,,")
    print(err)

```
<br>

3. 다른 예외 경우 예시

```python
try:
    number = input("100으로 나눌 숫자를 넣어봐")
    print(100 / int(number))

# 1. 0으로 나누는 경우라면?
# 2. 숫자가 아닌 문자열을 입력하는 경우라면?

try:  # 0이나 문자 둘 중 해당하는 곳으로 처리도 가능
    print(100 / 0) # or (100 / "0")를 입력한다면?

except ZeroDivisionError: # 0으로 나누는 경우
    print("0으로 대체 어케 나눔?")

except ValueError: # 숫자가 아닌 문자열을 입력하는 경우
    print("숫자만 입력해주세요")

# 그냥 간편하게 하나로 쓰고 싶으면
except (ZeroDivisionError, ValueError):
    print("너 잘못 입력했어")

# 모든 예외를 처리하고 싶으면
except Exception:
    print("무슨 에러인지는 모르겠는데 하여튼 잘못 됨")
```


**상속 순서 ▼**
```
Exception (최상위)
│
├─── ValueError
│
└─── ZeroDivisionError
```

**Exception을 먼저 처리하면 나머지 예외는 처리하지 않는다.**

 <br>

그래서 3가지 모두 실행하고 싶다면 ▼

```python
try:
    print(100 / 0)

except ZeroDivisionError: # 가장 구체적인 예외
    print("마지막 자식")
except ValueError: # 그 다음 구체적인 예외
    print("장남")
except Exception: # 모든 예외의 부모 클래스 (가장 일반적)
    print("부모")


# ⚠ 만약 Exception을 먼저 처리해버리면
try:
    print(100 / 0)
except Exception:    # 모든 예외가 여기서 잡혀버림
    print("부모")
except ValueError:   # 절대 실행되지 않음
    print("장남")
except ZeroDivisionError:   # 절대 실행되지 않음
    print("마지막 자식")

# 이렇게 되면 모든 예외를 처리하지 못하게 된다.
```


<br>


4.파일 처리를 위한 예외 처리

```python
try:
    # 내가 실행할 구문
    # 파일을 여는 코드
    file = open("test.txt", "r")

except:
    # try 구문에서 예외가 발생한 경우 실행할 구문
    # 파일이 없는 경우의 예외를 여기서 처리
    pass

else:
    # try 구문에서 예외가 발생하지 않은 경우 실행할 구문
    file.close()
    pass

finally:
    # 예외가 발생하던 안하던 무조건 실행되는 구문
    print("파일 열기 로직이 실행됨")
    pass
```

<br>

예외처리에 대해 알아보았고, 더 자세한 내용이나 상속 관계에 대해 알고 싶다면 아래 링크에서 확인 가능.

[▶ 예외처리 관련 링크](https://docs.python.org/ko/3/tutorial/errors.html)
